Repository codeready-toolchain/member-operator, pull requests merged in 2019-07, with the labels that each got.

#31 chore: build binary under 'build' dir
  make/format.mk
  make/go.mk
  make/out.mk
  openshift-ci/Dockerfile.deploy
Labels: approved, size/S

#32 Fix race condition in UserAccount controller
  go.mod
  go.sum
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, size/L

#29 chore: add 'make test-e2e'
  README.adoc
  build/Dockerfile
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  make/docker.mk
  make/test.mk
  openshift-ci/Dockerfile.deploy
  test/e2e/doc.go
Labels: approved, size/L

#26 e2e test
  README.adoc
  deploy/role.yaml
  go.sum
  make/test.mk
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
  test/e2e/doc.go
  test/e2e/main_test.go
  test/e2e/useraccount_test.go
  test/e2e/wait_util.go
Labels: approved, size/L

#30 Switch UserAccount to Status Conditions
  deploy/crds/toolchain_v1alpha1_useraccount.yaml
  go.mod
  go.sum
  make/clean.mk
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
  test/e2e/useraccount_test.go
  test/e2e/wait_util.go
Labels: approved, size/XL

#36 include 'jq' in CI tools
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#34 upload coverage reports using OpenShift CI env vars
  make/test.mk
Labels: approved, size/M

#37 change due to api make genreate
  deploy/crds/toolchain_v1alpha1_useraccount.yaml
Labels: approved, size/XS
