Repository codeready-toolchain/member-operator, pull requests merged in 2019-10, with the labels that each got.

#71 chore: add support for Go 1.13
  README.adoc
  go.mod
  go.sum
Labels: approved, size/S

#66 chore: clone the whole toolchain-e2e repo to make merging easier
  make/test.mk
Labels: approved, size/XS

#70 Fix make deploy-crd
  make/dev.mk
Labels: approved, size/XS

#73 add commit and buildtime vars
  cmd/manager/main.go
  cmd/manager/main_test.go
Labels: approved, size/M

#74 fix: handle makefile replacement of $ sign and don't commit while merging
  make/test.mk
Labels: approved, size/XS

#76 Exclude cmd/manager (main) from coverage report
  .codecov.yaml
  make/test.mk
Labels: approved, size/XS

#75 update CRDs with extra annotations, generated with go 1.13
  deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml
Labels: approved, size/S

#72 chore(CRT-281): create KubeFedCluster CRD programmatically
  cmd/manager/main.go
  deploy/cluster_role.yaml
  deploy/crds/core_v1beta1_kubefedcluster_crd.yaml
  go.mod
  go.sum
Labels: approved, size/L

#78 chore: refactor main and add comments
  cmd/manager/main.go
Labels: approved, lgtm, size/M

#77 chore(CRT-228): create CSV for member-operator
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/member-operator/0.0.0/member-operator.v0.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/member-operator/0.0.1/member-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/olm-catalog/member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml
  deploy/olm-catalog/member-operator/member-operator.package.yaml
  hack/deploy_csv.yaml
  hack/install_operator.yaml
Labels: approved, lgtm, size/XXL

#79 chore(CRT-226): add targets that help with deploying/installing operator
  README.adoc
  make/dev.mk
  make/docker.mk
  make/test.mk
Labels: approved, lgtm, size/L

#53 User namespaces provisioning
  deploy/cluster_role.yaml
  deploy/olm-catalog/member-operator/0.0.1/member-operator.v0.0.1.clusterserviceversion.yaml
  examples/toolchain_v1alpha1_useraccount_cr.yaml
  go.sum
  hack/deploy_csv.yaml
  make/go.mk
  pkg/controller/add_useraccount.go
  pkg/controller/add_useraccountstatus.go
  pkg/controller/controller.go
  pkg/controller/nstemplateset/nstemplateset_controller.go
  pkg/controller/nstemplateset/nstemplateset_controller_test.go
  pkg/controller/nstemplateset/test-files/basic-code.yaml
  pkg/controller/nstemplateset/test-files/basic-dev.yaml
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
  pkg/template/processor_test.go
Labels: approved, size/XXL

#81 refactor Commit and BuildTime variables
  .dockerignore
  cmd/manager/main.go
  version/version.go
  version/version_test.go
Labels: approved, size/M

#82 configure golangci timeout
  .golangci.yml
  make/lint.mk
Labels: approved, size/XS

#84 update Commit and BuildTime ldflags to new pkg path (fix)
  make/go.mk
Labels: approved, size/XS

#86 chore(CRT-331): rename member-operator to toolchain-member-operator
  .codecov.yaml
  deploy/olm-catalog/member-operator/member-operator.package.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.0/toolchain-member-operator.v0.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml
  deploy/olm-catalog/toolchain-member-operator/toolchain-member-operator.package.yaml
  hack/deploy_csv.yaml
  hack/install_operator.yaml
Labels: approved, size/L
