Repository codeready-toolchain/member-operator, pull requests merged in 2019-08, with the labels that each got.

#41 add dev cluster deploymentconfig
  deploy/operator_dev_cluster.yaml
  make/deploy.mk
  make/dev.mk
Labels: approved, size/L

#35 add make target for deploy host and create kubefedcluster for e2e
  make/test.mk
  openshift-ci/Dockerfile.tools
Labels: approved, size/M

#43 fix: use scheme with registered types from api repo
  go.mod
  go.sum
  pkg/apis/addtoscheme_toolchain_v1alpha1.go
  pkg/apis/apis.go
Labels: approved, size/S

#39 CRT-175: Implement garbage collection for UserAccount
  deploy/role.yaml
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
  test/e2e/useraccount_test.go
  test/e2e/wait_util.go
Labels: approved, lgtm, size/L

#45 update operator-sdk to v0.10.0
  cmd/manager/main.go
  go.mod
  go.sum
  make/test.mk
  openshift-ci/Dockerfile.tools
Labels: approved, size/L

#46 feat(CRT-165): e2e test for KubeFedCluster controller
  go.mod
  go.sum
  make/test.mk
  test/e2e/kubefedcluster_test.go
Labels: approved, size/S

#47 feat: add/modify make targets to clean e2e namespaces
  make/test.mk
Labels: approved, size/S

#48 remove vendor support
  .codecov.yaml
  make/dev.mk
Labels: approved, lgtm, size/XS

#50 introduce go-bindata in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#51 chore: print logs when e2e tests fail & change variable names
  README.adoc
  make/test.mk
Labels: approved, size/M

#52 Update to latest common
  go.mod
  go.sum
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, lgtm, size/M

#54 chore: format & rename manageCleanUpLogic & go mod tidy
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/useraccount/useraccount_controller.go
  test/e2e/useraccount_test.go
Labels: approved, lgtm, size/L

#55 Update k8s to 1.13.4
  go.mod
  go.sum
Labels: approved, size/M

#57 preserve custom fields in CRDs
  deploy/crds/toolchain_v1alpha1_useraccount.yaml
Labels: approved, size/M

#58 add golangci linter
  .golangci.yml
Labels: approved, size/XS
