Repository codeready-toolchain/member-operator, pull requests merged in 2019-12, with the labels that each got.

#100 chore(CRT-356): move template.Processor logic to common
  go.mod
  go.sum
  pkg/controller/nstemplateset/nstemplateset_controller.go
  pkg/controller/nstemplateset/nstemplatetier.go
  pkg/controller/nstemplateset/nstemplatetier_test.go
  pkg/template/filter.go
  pkg/template/filter_test.go
  pkg/template/processor.go
  pkg/template/processor_test.go
Labels: approved, size/XXL

#101 Remove deprecated TargetCluster from MUR status
  go.mod
  go.sum
Labels: approved, size/L

#102 chore: reflect changes in hack resource names
  hack/deploy_csv.yaml
  hack/install_operator.yaml
Labels: approved, size/S

#106 More logs in case of failed MUR status update
  pkg/controller/useraccountstatus/useraccount_status_controller.go
Labels: approved, size/S

#107 Add missing Permissions to member operator SA
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  hack/deploy_csv.yaml
Labels: approved, size/S

#109 Add permissions to edit roles for operator SA
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M
