Repository codeready-toolchain/member-operator, pull requests merged in 2019-11, with the labels that each got.

#87 Regenerate manifests by controller-runtime 0.2
  deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#88 chore: drop 0.0.0 csv template thanks to operator-sdk 0.11.0
  deploy/olm-catalog/toolchain-member-operator/0.0.0/toolchain-member-operator.v0.0.0.clusterserviceversion.yaml
  openshift-ci/Dockerfile.tools
Labels: approved, size/L

#90 Switch to go 1.13 in builder image
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#91 fix(e2e): install gcc in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#89 Switch to Kube 1.14
  cmd/manager/main.go
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  examples/kubefedcluster_host.yaml
  examples/kubefedcluster_member.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/kubefedcluster.go
  pkg/controller/nstemplateset/nstemplateset_controller.go
  pkg/controller/nstemplateset/nstemplateset_controller_test.go
  pkg/controller/useraccount/useraccount_controller_test.go
  pkg/template/processor_test.go
  tools.go
Labels: approved, size/L

#93 chore: add tests checking updates of NSTemplateSet condition to provisioned
  pkg/controller/nstemplateset/nstemplateset_controller_test.go
Labels: approved, size/M

#94 (DO NOT MERGE) chore: deploy csv for every commit in master via travis-ci
  .travis.yml
  make/docker.mk
  make/find-tools.mk
Labels: approved, size/M

#96 chore: add CD status images
  README.adoc
Labels: approved, size/XS

#95 set resourceversion before updating
  pkg/template/processor.go
  pkg/template/processor_test.go
Labels: approved, size/M

#97 Add get/list permissions for routes to obtain console url
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved, size/S

#98 add missing permissions to serviceaccount
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M

#99 Update common
  go.mod
  go.sum
Labels: approved, size/S
