Repository codeready-toolchain/member-operator, pull requests merged in 2019-09, with the labels that each got.

#59 fix JSONPath syntax for additionalPrinterColumns
  deploy/crds/toolchain_v1alpha1_useraccount.yaml
Labels: approved, size/XS

#61 chore: replace git.apache.org/thrift.git by github.com/apache/thrift
  go.mod
Labels: approved, size/XS

#62 check unused params with golangci
  .golangci.yml
  go.mod
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccountstatus/useraccount_status_controller_test.go
Labels: approved, size/M

#60 chore(CRT-222): move e2e tests to toolchain-e2e repo
  README.adoc
  go.mod
  make/test.mk
  test/e2e/doc.go
  test/e2e/kubefedcluster_test.go
  test/e2e/main_test.go
  test/e2e/useraccount_test.go
  test/e2e/wait_util.go
Labels: approved, lgtm, size/XL

#63 add func to retrieve templates from NSTemplateTier on host
  go.mod
  go.sum
  pkg/controller/useraccountstatus/useraccount_status_controller_test.go
  pkg/template/nstemplatetier.go
  pkg/template/nstemplatetier_test.go
Labels: approved, size/L

#64 chore: when running in CI use built image in e2e tests
  make/test.mk
Labels: approved, size/XS

#65 chore: install newer git and allow unrelated histories while merging
  make/test.mk
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS, ¯\_(ツ)_/¯

#67 Add vendor to codecov and yamllint ingore
  .codecov.yaml
  .yamllint
Labels: approved, size/XS

#68 refactor processor after NSTemplateTier changes
  deploy/crds/toolchain_v1alpha1_nstemplateset.yaml
  go.mod
  go.sum
  pkg/template/nstemplatetier.go
  pkg/template/nstemplatetier_test.go
  pkg/template/processor.go
  pkg/template/processor_test.go
Labels: approved, size/XL

#69 chore: add crd suffix to CRD file names-it's expected by operator-sdk csv generator
  deploy/crds/core_v1beta1_kubefedcluster_crd.yaml
  deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml
Labels: approved, size/XS
