Repository codeready-toolchain/member-operator, pull requests merged in 2019-06, with the labels that each got.

#14 revert Dockerfile as symbolic link is not working for operator-sdk build
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
Labels: approved, size/M

#16 Rename CRD files to align with api generator
  deploy/crds/toolchain_v1alpha1_nstemplateset.yaml
  deploy/crds/toolchain_v1alpha1_useraccount.yaml
Labels: approved, lgtm, size/M

#17 useraccount ctrl added with noop
  go.mod
  go.sum
  pkg/apis/addtoscheme_toolchain_v1alpha1.go
  pkg/controller/add_useraccount.go
  pkg/controller/useraccount/useraccount_controller.go
Labels: approved, lgtm, size/L

#18 fix: add toolchain.dev.openshift.com group to member-operator role
  deploy/role.yaml
Labels: approved, size/XS

#19 Add UserID to UserAccount
  deploy/crds/toolchain_v1alpha1_useraccount.yaml
  examples/toolchain_v1alpha1_useraccount_cr.yaml
Labels: approved, lgtm, size/XS

#15 feat(CRT-143): add KubeFedCluster CRD & controller
  Makefile
  README.adoc
  cmd/manager/main.go
  deploy/crds/core_v1beta1_kubefedcluster.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  examples/kubefedcluster_host.yaml
  examples/kubefedcluster_member.yaml
  go.mod
  go.sum
  make/dev.mk
  pkg/controller/add_kubefedcluster.go
  pkg/controller/controller.go
Labels: approved, lgtm, size/XL

#21 reorg makefiles and setup codecov
  .codecov.yaml
  .yamllint
  Makefile
  README.adoc
  make/clean.mk
  make/dev.mk
  make/find-tools.mk
  make/format.mk
  make/git.mk
  make/go.mk
  make/help.mk
  make/lint.mk
  make/out.mk
  make/test.mk
  make/verbose.mk
Labels: approved, size/L

#20 enhance useraccont ctrl
  examples/toolchain_v1alpha1_useraccount_cr.yaml
  go.mod
  go.sum
  pkg/apis/apis.go
  pkg/config/constants.go
  pkg/config/env.go
  pkg/controller/add_kubefedcluster.go
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, size/XL

#23 fix: exclude vendor dir from files to be formatted
  gofmt_exclude
  make/format.mk
Labels: approved, size/XS

#24 changed to toolchain-common
  README.adoc
  make/dev.mk
Labels: approved, size/S

#22 feat(CRT-150): add caching controller for KubeFedCluster CRs
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/kubefedcluster.go
Labels: approved, size/L

#28 separate goal to upload codecov report
  make/test.mk
Labels: approved, size/M

#27 feat(CRT-146): add sync update logic updating MasterUserRecord in host
  go.mod
  go.sum
  pkg/controller/add_useraccountstatus.go
  pkg/controller/useraccountstatus/useraccount_status_controller.go
  pkg/controller/useraccountstatus/useraccount_status_controller_test.go
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
Labels: approved, lgtm, size/L

#25 Improve status update error handling in UserAccount controller
  go.mod
  go.sum
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, lgtm, size/L
