Repository codeready-toolchain/member-operator, pull requests merged in 2020-03, with the labels that each got.

#129 feat(CRT-474): support promotion to other tiers
  go.mod
  go.sum
  pkg/controller/nstemplateset/nstemplateset_controller.go
  pkg/controller/nstemplateset/nstemplateset_controller_test.go
  pkg/controller/nstemplateset/test-files/basic-code.yaml
  pkg/controller/nstemplateset/test-files/basic-dev.yaml
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, size/XL

#130 add 'clusterResources' field in NSTemplateSet
  deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M

#132 add limit ranges on namespace templates
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved

#133 Add * permissions for NetworkPolicy to SA role
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved

#134 refactor NSTemplateSet tests using assertions
  go.mod
  go.sum
  pkg/controller/nstemplateset/nstemplateset_controller.go
  pkg/controller/nstemplateset/nstemplateset_controller_test.go
  test/namespace_assertion.go
  test/nstemplateset_assertion.go
Labels: approved

#135 fix: update api repo
  go.mod
  go.sum
  make/test.mk
Labels: approved

#128 Update operator-sdk to 0.15.2
  .travis.yml
  deploy/olm-catalog/csv-config.yaml
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#137 Fix operator-sdk key
  .travis.yml
  openshift-ci/Dockerfile.tools
Labels: approved
