Repository codeready-toolchain/member-operator, pull requests merged in 2020-02, with the labels that each got.

#105 Disabling useraccount
  go.mod
  go.sum
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, size/XL

#121 refactor NSTemplateSet/Namespace ownership
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/nstemplateset/nstemplateset_controller.go
  pkg/controller/nstemplateset/nstemplateset_controller_test.go
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, size/XL

#124 chore: add manifests targets & operator-courier to tools
  .travis.yml
  README.adoc
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
  make/manifests.mk
  openshift-ci/Dockerfile.tools
Labels: approved, size/L

#125 Update to new UserAccount API in tests
  deploy/olm-catalog/csv-config.yaml
  go.mod
  go.sum
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, size/M

#126 Update to Kube 1.16.2
  deploy/crds/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/crds/toolchain_v1alpha1_useraccount_crd.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_nstemplateset_crd.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain_v1alpha1_useraccount_crd.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/useraccount/useraccount_controller.go
  pkg/controller/useraccount/useraccount_controller_test.go
Labels: approved, size/XL
