Repository codeready-toolchain/member-operator, pull requests merged in 2020-01, with the labels that each got.

#110 Permission error in member
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved, size/S

#113 fix: use toolchain apis for listing CRs to be monitored
  cmd/manager/main.go
Labels: approved, size/XS

#114 chore: update api repo to use openshift/api@release-4.2
  go.mod
  go.sum
Labels: approved, size/S

#115 fix: common api sheme contain only CRs
  go.mod
  go.sum
  pkg/apis/apis.go
Labels: approved, size/S

#116 chore: remove unneeded permissons
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-member-operator/0.0.1/toolchain-member-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#117 Add `toolchain.dev.openshift.com/` prefix to namespace labels
  go.mod
  go.sum
  pkg/controller/nstemplateset/nstemplateset_controller.go
  pkg/controller/nstemplateset/nstemplateset_controller_test.go
Labels: approved, size/M

#118 Using reasons in api
  go.mod
  go.sum
  pkg/controller/useraccount/useraccount_controller.go
Labels: approved, size/S

#120 chore: install github.com/kislyuk/yq binary
  .travis.yml
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS
