Repository codeready-toolchain/member-operator, pull requests merged in 2022-10, with the labels that each got.

#383 build: upgrade Go 1.17 and k8s.io v0.23.5
  .github/workflows/ci-build.yml
  .github/workflows/operator-cd.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
  README.adoc
  go.mod
  go.sum
  make/get-tool.mk
  openshift-ci/Dockerfile.tools
Labels: approved

#387 fix(#343): Add permissions to scale Camel K resources
  config/rbac/camel_k_role.yaml
  config/rbac/camel_k_role_binding.yaml
  config/rbac/kustomization.yaml
Labels: approved, lgtm, ok-to-test

#388 fix(#343): Support scale resources that do not have specReplicasPath field set
  controllers/idler/idler_controller.go
  controllers/idler/idler_controller_test.go
Labels: approved, ok-to-test
