Repository codeready-toolchain/member-operator, pull requests merged in 2023-09, with the labels that each got.

#471 added PropagatedClaims to UserAccount type
  config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
Labels: approved

#470 feat: make SpaceBindingRequest.Spec.MasterUserRecord immutable
  cmd/webhook/main.go
  deploy/webhook/member-operator-webhook.yaml
  make/go.mk
  pkg/webhook/deploy/deployment.go
  pkg/webhook/deploy/deployment_test.go
  pkg/webhook/validatingwebhook/test/objectmocks.go
  pkg/webhook/validatingwebhook/test/verify_utils.go
  pkg/webhook/validatingwebhook/validate_checluster_request_test.go
  pkg/webhook/validatingwebhook/validate_rolebinding_request_test.go
  pkg/webhook/validatingwebhook/validate_spacebindingrequest.go
  pkg/webhook/validatingwebhook/validate_spacebindingrequest_test.go
Labels: approved

#473 Added email address to propagated claims
  config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
Labels: approved

#472 feat: add binding list to workspaces api
  config/crd/bases/toolchain.dev.openshift.com_workspaces.yaml
  go.mod
  go.sum
Labels: approved, lgtm

#474 update to support list of emails
  controllers/idler/idler_controller_test.go
  go.mod
  go.sum
Labels: approved, lgtm

#475 fix: go vet
  make/go.mk
  pkg/webhook/deploy/deployment.go
Labels: approved, ok-to-test
