Repository codeready-toolchain/member-operator, pull requests merged in 2023-11, with the labels that each got.

#492 complete bad fix
  make/test.mk
Labels: lgtm

#490 Update VM webhook to add cloud init user data
  controllers/memberoperatorconfig/memberoperatorconfig_controller.go
  controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go
  pkg/webhook/mutatingwebhook/mutate.go
  pkg/webhook/mutatingwebhook/mutate_test.go
  pkg/webhook/mutatingwebhook/userpods_mutate.go
  pkg/webhook/mutatingwebhook/userpods_mutate_test.go
  pkg/webhook/mutatingwebhook/vm_mutate.go
  pkg/webhook/mutatingwebhook/vm_mutate_test.go
Labels: approved

#488 disable HTTP/2 on kube-rbac-proxy container
  config/manager/manager.yaml
Labels: approved

#491 Generated api update for webhook configuration
  config/crd/bases/toolchain.dev.openshift.com_memberoperatorconfigs.yaml
Labels: approved

#494 fix: forward context in useraccount reconciler
  controllers/useraccount/useraccount_controller.go
  controllers/useraccount/useraccount_controller_test.go
Labels: approved

#499 fix: forward context into pkgs
  controllers/memberoperatorconfig/memberoperatorconfig_controller.go
  controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/cert/secret.go
  pkg/cert/secret_test.go
  pkg/utils/route/route.go
  pkg/utils/route/route_test.go
  pkg/webhook/deploy/deployment.go
  pkg/webhook/deploy/deployment_test.go
Labels: approved, lgtm

#498 fix: forward context in NSTemplateSet reconciler
  controllers/nstemplateset/client.go
  controllers/nstemplateset/client_test.go
  controllers/nstemplateset/cluster_resources.go
  controllers/nstemplateset/cluster_resources_test.go
  controllers/nstemplateset/namespaces.go
  controllers/nstemplateset/namespaces_test.go
  controllers/nstemplateset/nstemplateset_controller.go
  controllers/nstemplateset/nstemplatetier.go
  controllers/nstemplateset/nstemplatetier_test.go
  controllers/nstemplateset/space_roles.go
  controllers/nstemplateset/space_roles_test.go
  controllers/nstemplateset/status.go
  controllers/nstemplateset/status_test.go
Labels: approved

#497 fix: forward context in memberstatus reconciler
  controllers/memberstatus/memberstatus_controller.go
Labels: approved, lgtm

#500 add disable inheritance api
  config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml
Labels: approved

#496 Get config in webhook
  cmd/consoleplugin/main.go
  cmd/webhook/main.go
  controllers/memberoperatorconfig/configuration.go
  controllers/memberoperatorconfig/configuration_test.go
  controllers/memberoperatorconfig/mapper_test.go
  controllers/memberoperatorconfig/memberoperatorconfig_controller.go
  controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go
  controllers/memberstatus/creation_test.go
  controllers/memberstatus/memberstatus_controller.go
  controllers/memberstatus/memberstatus_controller_test.go
  controllers/useraccount/useraccount_controller.go
  controllers/useraccount/useraccount_controller_test.go
  deploy/webhook/member-operator-webhook.yaml
  go.mod
  go.sum
  main.go
  pkg/consoleplugin/consolepluginserver.go
  pkg/consoleplugin/consolepluginserver_test.go
  pkg/webhook/deploy/deployment_test.go
  pkg/webhook/mutatingwebhook/vm_mutate.go
  pkg/webhook/mutatingwebhook/vm_mutate_test.go
Labels: approved

#495 fix: forward context in idler reconciler
  controllers/idler/idler_controller.go
  controllers/idler/idler_controller_test.go
Labels: approved, lgtm

#493 Adds a webhook to prevent regular users from creating a KubernetesImagePuller resource
  cmd/webhook/main.go
  deploy/webhook/member-operator-webhook.yaml
  pkg/webhook/deploy/deployment_test.go
  pkg/webhook/validatingwebhook/validate_k8simagepuller_request.go
  pkg/webhook/validatingwebhook/validate_k8simagepuller_request_test.go
Labels: approved, ok-to-test

#502 fix: forward context in toolchain-common pkg/client
  controllers/memberoperatorconfig/memberoperatorconfig_controller.go
  controllers/memberoperatorconfig/memberoperatorconfig_controller_test.go
  controllers/memberstatus/creation.go
  controllers/memberstatus/creation_test.go
  controllers/nstemplateset/client.go
  controllers/nstemplateset/client_test.go
  controllers/nstemplateset/cluster_resources.go
  go.mod
  go.sum
  main.go
  pkg/autoscaler/autoscaler.go
  pkg/autoscaler/autoscaler_test.go
  pkg/consoleplugin/deploy/deployment.go
  pkg/consoleplugin/deploy/deployment_test.go
  pkg/webhook/deploy/deployment.go
Labels: approved

#506 Vm Idler
  controllers/idler/idler_controller.go
  controllers/idler/idler_controller_test.go
  main.go
  test/idler_assertion.go
Labels: approved

#505 fix: forward context in GH client
  controllers/memberstatus/memberstatus_controller.go
  go.mod
  go.sum
Labels: approved

#509 fix: forward context in idler reconciler
  controllers/idler/idler_controller.go
Labels: approved, lgtm

#507 refactored member operator to only use properties from propagated claims
  controllers/useraccount/useraccount_controller.go
  controllers/useraccount/useraccount_controller_test.go
Labels: approved

#510 Don't use email annotation, use PropagatedClaims instead
  controllers/useraccount/useraccount_controller.go
  controllers/useraccount/useraccount_controller_test.go
Labels: approved
