Repository codeready-toolchain/member-operator, pull requests merged in 2023-10, with the labels that each got.

#479 fix: switch sbr webhook to fail policy, add some comments
  deploy/webhook/member-operator-webhook.yaml
  pkg/webhook/deploy/deployment_test.go
  pkg/webhook/validatingwebhook/validate_spacebindingrequest.go
Labels: approved

#480 fix: add missing binding request field
  config/crd/bases/toolchain.dev.openshift.com_workspaces.yaml
  go.mod
  go.sum
Labels: approved

#481 ci: bump actions to silence node12 warnings
  .github/workflows/ci-build.yml
  .github/workflows/ci-check-gomod.yml
  .github/workflows/operator-cd.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
Labels: approved, lgtm, ok-to-test

#482 fix: add missing open api marker to ws structs
  config/crd/bases/toolchain.dev.openshift.com_workspaces.yaml
  go.mod
  go.sum
Labels: approved

#476 Remove unused code for devspace endpoints
  controllers/memberstatus/memberstatus_controller.go
  controllers/memberstatus/memberstatus_controller_test.go
  controllers/useraccount/useraccount_controller.go
  controllers/useraccount/useraccount_controller_test.go
  go.mod
  main.go
  pkg/che/che.go
  pkg/che/che_test.go
  pkg/che/tokencache.go
  pkg/che/tokencache_test.go
Labels: approved, lgtm, ok-to-test

#483 Set threshold to 1%
  .codecov.yaml
Labels: approved, lgtm

#484 add CODEOWNERS file
  CODEOWNERS
Labels: approved

#477 Vm webhook limits
  cmd/webhook/main.go
  deploy/webhook/member-operator-webhook.yaml
  pkg/webhook/deploy/deployment_test.go
  pkg/webhook/mutatingwebhook/mutate.go
  pkg/webhook/mutatingwebhook/mutate_test.go
  pkg/webhook/mutatingwebhook/userpods_mutate.go
  pkg/webhook/mutatingwebhook/userpods_mutate_test.go
  pkg/webhook/mutatingwebhook/vm_mutate.go
  pkg/webhook/mutatingwebhook/vm_mutate_test.go
Labels: approved

#486 webhooks: disable HTTP/2
  cmd/webhook/main.go
Labels: approved

#487 update kube-rbac-proxy to v4.13.0
  config/manager/manager.yaml
Labels: approved, lgtm

#489 get pr branch name from CLONEREFS_OPTIONS
  make/test.mk
Labels: approved

#485 No Notification for "Completed" and without controller Pods
  controllers/idler/idler_controller.go
  controllers/idler/idler_controller_test.go
Labels: approved
