Repository codeready-toolchain/member-operator, pull requests merged in 2023-05, with the labels that each got.

#435 add permissions (and ClusterRole) needed to apply appstudio tenant tier
  config/rbac/appstudio_pipelines_runner_binding.yaml
  config/rbac/appstudio_pipelines_runner_role.yaml
  config/rbac/kustomization.yaml
Labels: approved

#430 chore(webconsole): build assets with ubi8/nodejs-16
  make/webconsole.mk
  webconsole_source/Containerfile
  webconsole_source/package.json
Labels: approved

#439 Allow pipelines-scc for appstudio_pipelines_runner_role
  config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
Labels: approved, lgtm, ok-to-test

#437 fix: rename USERNAME template parameter with SPACE_NAME
  controllers/nstemplateset/cluster_resources.go
  controllers/nstemplateset/cluster_resources_test.go
  controllers/nstemplateset/namespaces.go
  controllers/nstemplateset/namespaces_test.go
  controllers/nstemplateset/nstemplateset_controller.go
  controllers/nstemplateset/nstemplateset_controller_test.go
  controllers/nstemplateset/nstemplatetier_test.go
  controllers/nstemplateset/space_roles.go
  controllers/nstemplateset/status_test.go
Labels: approved

#441 Allow ECP access to appstudio-pipelines-runner
  config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
Labels: approved, ok-to-test

#443 Rename pipelines-scc to appstudio-pipelines-scc 1/2
  config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
Labels: approved, lgtm, ok-to-test
