Repository codeready-toolchain/member-operator, pull requests merged in 2024-02, with the labels that each got.

#522 Removed unused token claim properties from API
  config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
  controllers/useraccount/useraccount_controller.go
  controllers/useraccount/useraccount_controller_test.go
  go.mod
  go.sum
Labels: approved

#532 webconsole: upgrade NPM modules
  .gitignore
  webconsole_source/yarn.lock
Labels: approved

#529 chore(RHTAPWATCH-765): appstudio-pipeline can manage SpaceRequests
  config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
Labels: approved, lgtm, needs-ok-to-test

#533 chore: grant pipelines-runner additional spacerequest permissions
  config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml
Labels: approved, ok-to-test

#534 Handle when domain memory request is set
  pkg/webhook/mutatingwebhook/vm_mutate.go
  pkg/webhook/mutatingwebhook/vm_mutate_test.go
Labels: approved

#535 Ensure sandbox toleration
  pkg/webhook/mutatingwebhook/vm_mutate.go
  pkg/webhook/mutatingwebhook/vm_mutate_test.go
Labels: approved
