Repository codeready-toolchain/member-operator, pull requests merged in 2024-01, with the labels that each got.

#517 fix: forward context in validatingwebhooks
  pkg/webhook/validatingwebhook/validate_k8simagepuller_request.go
  pkg/webhook/validatingwebhook/validate_k8simagepuller_request_test.go
  pkg/webhook/validatingwebhook/validate_rolebinding_request.go
  pkg/webhook/validatingwebhook/validate_rolebinding_request_test.go
  pkg/webhook/validatingwebhook/validate_spacebindingrequest.go
  pkg/webhook/validatingwebhook/validate_spacebindingrequest_test.go
Labels: approved

#524 upgrade ose-kube-rbac-proxy to v4.14
  config/manager/manager.yaml
Labels: approved, lgtm

#523 Regenerated from API changes
  config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
Labels: approved

#525 Regenerated from API
  config/crd/bases/toolchain.dev.openshift.com_useraccounts.yaml
Labels: approved

#526 Remove kubernetesimagepuller webhook
  cmd/webhook/main.go
  deploy/webhook/member-operator-webhook.yaml
  pkg/webhook/deploy/deployment_test.go
  pkg/webhook/validatingwebhook/validate_k8simagepuller_request.go
  pkg/webhook/validatingwebhook/validate_k8simagepuller_request_test.go
Labels: approved, ok-to-test

#528 check substrings of GH comments to run PR CD workflow
  .github/workflows/publish-operators-for-e2e-tests.yml
Labels: approved

#527 Add webhook for CNV SSP resources
  cmd/webhook/main.go
  deploy/webhook/member-operator-webhook.yaml
  pkg/webhook/deploy/deployment_test.go
  pkg/webhook/validatingwebhook/validate_ssp_request.go
  pkg/webhook/validatingwebhook/validate_ssp_request_test.go
Labels: approved

#519 fix: forward context in common's status pkg
  controllers/memberstatus/memberstatus_controller.go
  go.mod
  go.sum
Labels: approved

#520 fix: forward context in common's notification pkg
  controllers/idler/idler_controller.go
  go.mod
  go.sum
Labels: approved
